select * from EMPLOYEE


select * from employee where HIREDATE between '20-feb-1981' and '12-jan-1982'


select * from employee where sal >= 2500 and DEPTNAME = 'INSURANCE'

SELECT * FROM EMPLOYEE WHERE ENAME LIKE 'J____'

SELECT * FROM EMPLOYEE WHERE ENAME LIKE 'A%'

SELECT * FROM EMPLOYEE WHERE SAL !> 2500

SELECT * FROM EMPLOYEE WHERE ENAME IN ('SMITH','JONES','ADAMS')

SELECT MIN(SAL),DEPTNAME FROM EMPLOYEE GROUP BY DEPTNAME

SELECT MAX(SAL),DEPTNAME FROM EMPLOYEE GROUP BY DEPTNAME

SELECT AVG(SAL) FROM EMPLOYEE

SELECT SUM(SAL) FROM EMPLOYEE

SELECT COUNT(DEPTNAME),MIN(SAL),DEPTNAME FROM EMPLOYEE GROUP BY DEPTNAME HAVING COUNT(DEPTNAME)> 1;
