use SQLSERVER;

create table EMPLOYEE
(
  EMPNO    INT not null,
  ENAME    VARCHAR(10),
  MGR      INT,
  HIREDATE DATE,
  SAL      INT,
  DEPTNAME VARCHAR(10)
);

EXEC sp_help 'EMPLOYEE';  -- TO VIEW TABLE STRUCTURE


insert into EMPLOYEE(EMPNO, ENAME, MGR, HIREDATE, SAL, DEPTNAME)
values (1, 'SMITH', 3, '17-DEC-1980', 800.00, 'BANKING');

insert into EMPLOYEE(EMPNO, ENAME, MGR, HIREDATE, SAL, DEPTNAME)
values (2, 'ALLEN', 4, '20-FEB-1981', 1600.00, 'INSURANCE');

insert into EMPLOYEE(EMPNO, ENAME, MGR, HIREDATE, SAL, DEPTNAME)
values (3, 'WARD', null,'22-FEB-1981', 1250.00, 'BANKING');

insert into EMPLOYEE(EMPNO, ENAME, MGR, HIREDATE, SAL, DEPTNAME)
values (4, 'JONES', null, '02-APR-1981', 2975.00, 'INSURANCE');

insert into EMPLOYEE(EMPNO, ENAME, MGR, HIREDATE, SAL, DEPTNAME)
values (5, 'MARTIN', 4,'28-NOV-1981', 1250.00, 'INSURANCE');

insert into EMPLOYEE(EMPNO, ENAME, MGR, HIREDATE, SAL, DEPTNAME)
values (6, 'BLAKE', 7,'01-MAY-1981', 2850.00, 'SERVICES');

insert into EMPLOYEE (EMPNO, ENAME, MGR, HIREDATE, SAL, DEPTNAME)
values (7, 'CLARK', null, '09-JUN-1981', 2450.00, 'SERVICES');

insert into EMPLOYEE(EMPNO, ENAME, MGR, HIREDATE, SAL, DEPTNAME)
values (8, 'SCOTT', 4, '09-DEC-1982', 3000.00, 'INSURANCE');

insert into EMPLOYEE(EMPNO, ENAME, MGR, HIREDATE, SAL, DEPTNAME)
values (9, 'KING', 3,'17-NOV-1981', 5000.00, 'BANKING');

insert into EMPLOYEE(EMPNO, ENAME, MGR, HIREDATE, SAL, DEPTNAME)
values (10, 'TURNER', 4,'08-SEP-1981', 1500.00, 'INSURANCE');

insert into EMPLOYEE(EMPNO, ENAME, MGR, HIREDATE, SAL, DEPTNAME)
values (11, 'ADAMS', 3, '12-JAN-1983', 1100.00, 'BANKING');

insert into EMPLOYEE(EMPNO, ENAME, MGR, HIREDATE, SAL, DEPTNAME)
values (12, 'JAMES', 7,'03-DEC-1981', 950.00, 'SERVICES');

insert into EMPLOYEE(EMPNO, ENAME, MGR, HIREDATE, SAL, DEPTNAME)
values (13, 'FORD', 4,'03-DEC-1981', 3000.00, 'INSURANCE');

insert into EMPLOYEE(EMPNO, ENAME, MGR, HIREDATE, SAL, DEPTNAME)
values (14, 'MILLER', 4,'23-JAN-1982', 1300.00, 'INSURANCE');

SELECT * FROM EMPLOYEE ORDER BY EMPNO DESC;
SELECT * FROM EMPLOYEE ORDER BY EMPNO;

SELECT * FROM EMPLOYEE;

SELECT name FROM sys.databases;  ---- TO VIEW ALL DATABASES IN SYSTEM

