CREATE PROCEDURE GETDATA 
AS
BEGIN
        SELECT * FROM STATES
END

GETDATA ------ EXCUTE

CREATE PROCEDURE EMPDATA
(
@DEPT_NAME VARCHAR(40)
)
AS
BEGIN
       SELECT * FROM EMPLOYEE WHERE DEPTNAME = @DEPT_NAME
END

EMPDATA 'BANKING' ---- EXCUTE